AppBundle\Entity\RecipesRecipe:
    exclusion_policy: none
    properties:
        id:
            groups: ['recipes', 'recipesName', 'userRecipes', 'postRecipe']
        name:
            groups: ['recipes', 'recipesName', 'userRecipes', 'postRecipe']
        slug:
            groups: ['recipes', 'recipesName', 'userRecipes', 'postRecipe']
        user:
            groups: ['recipesName', 'postRecipe']
        step:
            groups: ['recipesName', 'postRecipe']