AppBundle\Entity\UsersUser:
    exclusion_policy: none
    properties:
        username:
            groups: ['recipesByName', 'new_recipe']
        last_login:
            groups: ['recipesByName', 'new_recipe']
        id:
            groups: ['recipesByName', 'new_recipe']
        recipes:
            groups: []