AppBundle\Entity\UsersUser:
    exclusion_policy: none
    properties:
        username:
            groups: ['recipesName', 'postRecipe']
        last_login:
            groups: ['recipesName', 'postRecipe']
        id:
            groups: ['recipesName', 'postRecipe']
        recipes:
            groups: []